"use client";

import {
  Baby,
  Banknote,
  Bike,
  Book,
  Briefcase,
  Car,
  CircleDollarSign,
  Coffee,
  Coins,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Leaf,
  MoreHorizontal,
  Music,
  Palette,
  PawPrint,
  PiggyBank,
  Plane,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Ticket,
  TrainFront,
  Tv,
  Undo2,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
  CreditCard,
  Vault,
  TrendingUp,
  Shield,
  Target,
  Repeat,
  type LucideIcon,
} from "lucide-react";

/** Icônes disponibles pour les catégories, comptes et objectifs (importées explicitement pour garder un bundle léger). */
export const ICONS: Record<string, LucideIcon> = {
  Baby,
  Banknote,
  Bike,
  Book,
  Briefcase,
  Car,
  CircleDollarSign,
  Coffee,
  Coins,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Leaf,
  MoreHorizontal,
  Music,
  Palette,
  PawPrint,
  PiggyBank,
  Plane,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Ticket,
  TrainFront,
  Tv,
  Undo2,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
  CreditCard,
  Vault,
  TrendingUp,
  Shield,
  Target,
  Repeat,
};

export function IconByName({ name, className, size = 18 }: { name: string; className?: string; size?: number }) {
  const Icon = ICONS[name] ?? MoreHorizontal;
  return <Icon className={className} size={size} strokeWidth={2} aria-hidden />;
}

export const ACCOUNT_TYPE_ICON: Record<string, string> = {
  checking: "Wallet",
  savings: "PiggyBank",
  cash: "Banknote",
  card: "CreditCard",
  investment: "TrendingUp",
  pillar3a: "Shield",
};

export const ACCOUNT_TYPE_LABEL: Record<string, string> = {
  checking: "Compte courant",
  savings: "Épargne",
  cash: "Cash",
  card: "Carte de crédit",
  investment: "Investissements",
  pillar3a: "Pilier 3a",
};
